version: '3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=123
      - SECRET_KEY=super_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db: